//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOffice.Desktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbProjectOfficeEntities : DbContext
    {
        public DbProjectOfficeEntities()
            : base("name=DbProjectOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Emploeyy> Emploeyy { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<StoryTaskStatus> StoryTaskStatus { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskStatus> TaskStatus { get; set; }
    }
}
