//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOffice.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string SendTime { get; set; }
        public int TaskId { get; set; }
        public int EmploeyyId { get; set; }
        public string Text { get; set; }
    
        public virtual Emploeyy Emploeyy { get; set; }
        public virtual Task Task { get; set; }
    }
}
