//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOffice.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Attachment = new HashSet<Attachment>();
            this.Comment = new HashSet<Comment>();
            this.StoryTaskStatus = new HashSet<StoryTaskStatus>();
            this.Task1 = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string FullTitle { get; set; }
        public string ShortTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExecutiveEmployeeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> SratActualTime { get; set; }
        public Nullable<System.DateTime> FinishActualTime { get; set; }
        public Nullable<int> PreviosTaskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Emploeyy Emploeyy { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryTaskStatus> StoryTaskStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task1 { get; set; }
        public virtual Task Task2 { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual Emploeyy Emploeyy1 { get; set; }
    }
}
